### PR TITLE
#163391969 create a signup page

### PR DESCRIPTION
**Pull request by vkingmaker**
#### What does this PR do?
- Add a signup page to the project to from where users can signup to use the application
#### Description of Task to be completed?
`/GET /signup.html`
#### How should this be manually tested?
- After cloning the repository
- `cd` into the project.
- run a local server to host the app locally. 
- using your favorite browser visit the link above.
#### What are the relevant pivotal tracker stories?
 #163391969
#### Screenshots
signup

### CODE REVIEW

**Comment by megame24** [comment]
Why do you have a merge commit on this PR?

**Comment by vkingmaker** [comment]
I resolved a merge conflict with the develop branch, I could not effect the resolved conflict without committing the merge. Is that a problem?

**Comment by megame24** [comment]
> I resolved a merge conflict with the develop branch, I could not effect the resolved conflict without committing the merge. Is that a problem?

It is not a problem, try and perfect your Git workflow, which should eliminate merge conflicts. Since you are the only one working on this repo, you should have little to no merge conflict.

**Review by megame24 — APPROVED** [review]
Looks good, you can merge.

**Pull request merged**
