### PR TITLE
#163503528 add a POST endpoint to create a political party

### PR DESCRIPTION
**Pull request by vkingmaker**
#### What does this PR do?
- Add an endpoint with `POST` method to enable admin create apolitical Party
#### Description of Task to be completed?
`POST /api/v1/parties` 
#### How should this be manually tested?
- After cloning the repository
- `cd` into the project.
- run `npm install` or `yarn install` to install dependencies. 
- run `npm run start` to start up the server
- using postman and test the endpoint above
#### What are the relevant pivotal tracker stories?
#163503528

### CODE REVIEW

**Comment by megame24** [comment]
Why do you have 133 file changes, I can see changes that is not related to creating a political party.

**Comment by vkingmaker** [comment]
I Had to set up everything I will need for my test suites and documentation
so I included all the files for travis, coverall, an apiDocs

**Comment by megame24** [comment]
> I Had to set up everything I will need for my test suites and documentation
> so I included all the files for travis, coverall, an apiDocs

I've told you this earlier, but just to reiterate, try as much as possible to create separate stories to handle separate tasks.

**Comment by vkingmaker** [comment]
Ok thank You

**Comment by vkingmaker** [comment]
I just ignore some of the generated folders and environment files to reduce the number of files I am pushing to the repository

**Pull request merged**
